ARG ORB_TAG=develop
ARG PKTVISOR_TAG=develop
ARG DIODE_TAG=develop
ARG OTEL_TAG=0.91.0
ARG OTEL_DOCKER_REPO=otel/opentelemetry-collector-contrib
ARG OTELCONTRIB_ENTRYPOINT=/usr/local/bin/otelcol-contrib

FROM orbcommunity/orb-agent:${ORB_TAG} AS orb

FROM orbcommunity/diode-agent:${DIODE_TAG} AS diode

FROM ${OTEL_DOCKER_REPO}:${OTEL_TAG} AS otelcol-contrib

FROM orbcommunity/pktvisor:${PKTVISOR_TAG}

# adding orb-agent
RUN mkdir /opt/orb
COPY --from=orb /usr/local/bin/orb-agent /usr/local/bin/orb-agent
COPY ./agent/docker/agent_default_full.yaml /opt/orb/agent_default.yaml
COPY --from=orb /usr/local/bin/orb-agent-entry.sh /usr/local/bin/orb-agent-entry.sh
COPY --from=orb /run-agent.sh /run-agent.sh

# adding diode-agent
COPY --from=diode /usr/local/bin/diode-agent /usr/local/bin/diode-agent

# adding suzieq patched
COPY --from=diode /root/.suzieq /root/.suzieq

COPY --from=otelcol-contrib ${OTELCONTRIB_ENTRYPOINT} /usr/local/bin/otelcol-contrib

RUN chmod a+x /run-agent.sh

ENTRYPOINT [ "/usr/local/bin/orb-agent-entry.sh" ]
