name: Go

on:
  workflow_dispatch:
    inputs:
      pktvisor_tag:
        description: 'pktvisor agent docker tag to package'
        required: true
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  trigger-build-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            agent:
              - 'agent/**'
              - 'cmd/agent/**'
            orb:
              - 'fleet/**'
              - 'cmd/fleet/**'
              - 'policies/**'
              - 'cmd/policies/**'
              - 'sinks/**'
              - 'cmd/sinks/**'
              - 'sinker/**'
              - 'cmd/sinker/**'
              - 'ui/**'
    outputs:
      should-build-agent: ${{ steps.changes.outputs.agent }}
      should-build-orb: ${{ steps.changes.outputs.orb }}

  build-agent:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-agent == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build services (go build only)
        run: make agent

      - name: Build orb agent (go build only)
        if: steps.filter.outputs.agent == 'true'
        run: make agent_bin

      - name: Go unit tests
        run: SERVICE=agent make test_service

  build-fleet:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build services (go build only)
        run: make fleet

      - name: Go unit tests
        run: SERVICE=fleet make test_service

  build-policies:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build services (go build only)
        run: make policies

      - name: Go unit tests
        run: SERVICE=policies make test_service

  build-sinks:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build services (go build only)
        run: make sinks

      - name: Go unit tests
        run: SERVICE=sinks make test_service

  build-sinker:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-orb == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build services (go build only)
        run: make sinker

      - name: Go unit tests
        run: SERVICE=sinker make test_service

      - name: Upload sinker artifact
        uses: actions/upload-artifact@v3
        with:
          name:

  build-ui:
    runs-on: ubuntu-latest
    needs: trigger-build-services
    if: ${{ needs.trigger-build-services.outputs.should-build-agent == 'true' }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Build UI
        run: make ui

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ui
          path:

  package:
    needs: build
    runs-on: ubuntu-latest
    # if this is a push into one of our main branches (rather than just a pull request), we will also package
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            agent:
              - 'agent/**'
              - 'cmd/agent/**'
            fleet:
              - 'fleet/**'
              - 'cmd/fleet/**'
            policies:
              - 'policies/**'
              - 'cmd/policies/**'
            sinks:
              - 'sinks/**'
              - 'cmd/sinks/**'
            sinker:
              - 'sinker/**'
              - 'cmd/sinker/**'
            ui:
              - 'ui/**'

      - name: Set branch name
        shell: bash
        run: |
          echo "BRANCH_NAME=develop" >> $GITHUB_ENV

      - name: Generate ref tag (develop)
        run: |
          echo "REF_TAG=develop" >> $GITHUB_ENV

      - name: Append suffix on VERSION file for develop build
        run: |
          echo "`cat ${{github.workspace}}/VERSION`-${{ env.REF_TAG }}" > VERSION

      - name: Get VERSION
        run: |
          echo "VERSION=`cat ${{github.workspace}}/VERSION`" >> $GITHUB_ENV

      - name: Debug VERSION
        run: echo ${{ env.VERSION }}

      - name: Get short commit hash to a variable
        id: commit_hash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Commit orb-ui-live on orb-live repo develop
        run: |
          git config --global user.email "${{secrets.GH_ORB_EMAIL}}"
          git config --global user.name "${{secrets.GH_ORB_USER}}"
          git config --global credential.helper cache
          git clone -b develop https://${{secrets.GH_ORB_USER}}:${{secrets.GH_ORB_ACCESS_TOKEN}}@github.com/ns1labs/orb-live.git          
          cd orb-live
          cp -rf ../ui .
          cp -rf ../VERSION .
          echo "${{ steps.commit_hash.outputs.sha_short }}" > COMMIT_HASH          
          git add .
          git commit -m "[NS1 Orb Bot] Update Orb Live UI for develop"
          git push origin develop

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build service containers
        run: make dockers

      - name: Build orb-agent
        shell: bash
        if: steps.filter.outputs.agent == 'true'
        env:
          IMAGE_NAME: ns1labs/orb-agent
        run: |
          if [ "${{ github.event.inputs.pktvisor_tag }}" == "" ]; then
            make agent
            make agent_debug
          else
            PKTVISOR_TAG=${{ github.event.inputs.pktvisor_tag }} make agent
            PKTVISOR_TAG=${{ github.event.inputs.pktvisor_tag }} make agent_debug
          fi

      - name: Push agent container
        if: steps.filter.outputs.agent == 'true'
        run: |
          docker push -a ns1labs/orb-agent

      - name: Build orb-ui
        if: steps.filter.outputs.ui == 'true'
        env:
          IMAGE_NAME: ns1labs/orb-ui
        run: |
          make ui

      - name: Push ui container
        if: steps.filter.outputs.ui == 'true'
        run: |
          docker push -a ns1labs/orb-ui

      - name: Push service containers
        run: |
          docker push -a ns1labs/orb-fleet
          docker push -a ns1labs/orb-policies
          docker push -a ns1labs/orb-sinks
          docker push -a ns1labs/orb-sinker

      - name: Commit image tag on orb-live-manifest environment dev
        run: |
          git config --global user.email "${{secrets.GH_ORB_EMAIL}}"
          git config --global user.name "${{secrets.GH_ORB_USER}}"
          git config --global credential.helper cache
          git clone https://${{secrets.GH_ORB_USER}}:${{secrets.GH_ORB_ACCESS_TOKEN}}@github.com/ns1labs/orb-live-manifest.git
          cd orb-live-manifest/stg
          mv values.yaml .template/values.old
          cat .template/values.yaml.tpl >> values.yaml
          sed -i -e "s/IMAGE_TAG/${{ env.VERSION }}-${{ steps.commit_hash.outputs.sha_short }}/g" values.yaml
          git add values.yaml
          git add .template/values.old
          git commit -m "[NS1 Orb Bot] Update image tag on stg environment"
          git push origin main
